[sqs]
    [sqs.us_logs]
    queue_url = "https://sqs.ap-southeast-1.amazonaws.com/971037846030/test"
    region = "us-east-1"
    delete_msg = false

    [sqs.sg_logs]
    queue_url = "https://sqs.ap-southeast-1.amazonaws.com/971037846030/MAD_batman_3_craftsvilla_search"
    region = "ap-southeast-1"
    delete_msg = false

[jsonl]
    [jsonl.backup_logs]
    path = "/tmp/kulay.jsonl"